import type { MaterialProfile } from './pricing-types';

export const materialCatalogVersion = 2;

export const defaultMaterials: MaterialProfile[] = [
  {
    id: 'material1',
    name: '【灰琉璃】UFS3009',
    process: 'sla',
    description: '表面细腻光滑，灰度均匀，适合高精度外观件和展示模型',
    descriptionEn: 'Fine, smooth surface with uniform gray tone, suitable for high-precision appearance parts and display models',
    densityGPerCm3: 1.3,
    materialPricePerG: 1,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material2',
    name: '【高韧耐温料】UTRYG01',
    process: 'sla',
    description: '高韧性耐冲击，热变形温度高，适合功能性验证件和结构件',
    descriptionEn: 'High toughness and impact resistance with high heat deflection temperature, suitable for functional validation parts and structural parts',
    densityGPerCm3: 1.3,
    materialPricePerG: 0.6,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material3',
    name: '【高韧耐温料】Somos Taurus',
    process: 'sla',
    description: '优异的韧性和耐温性，抗冲击性强，适合耐用功能件和装配测试',
    descriptionEn: 'Excellent toughness and heat resistance with strong impact resistance, suitable for durable functional parts and assembly testing',
    densityGPerCm3: 1.3,
    materialPricePerG: 2,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material4',
    name: '【高韧耐温料】Somos Ledo',
    process: 'sla',
    description: '高韧性与高刚性平衡，耐化学性好，适合复杂功能结构件',
    descriptionEn: 'Balanced toughness and rigidity with good chemical resistance, suitable for complex functional structural parts',
    densityGPerCm3: 1.3,
    materialPricePerG: 1,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material5',
    name: '【透明料】UTR8100-全透',
    process: 'sla',
    description: '高透光率，透明度好，适合光学部件、透明外壳和展示模型',
    descriptionEn: 'High light transmittance and clarity, suitable for optical parts, transparent housings, and display models',
    densityGPerCm3: 1.3,
    materialPricePerG: 2.5,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material6',
    name: '【耐温料】UTR Therm1',
    process: 'sla',
    description: '热变形温度高，耐高温性能优异，适合高温环境下的功能件',
    descriptionEn: 'High heat deflection temperature and excellent heat resistance, suitable for functional parts in high-temperature environments',
    densityGPerCm3: 1.3,
    materialPricePerG: 1.5,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material7',
    name: '【透明料】UTR8100-半透',
    process: 'sla',
    description: '半透明磨砂效果，透光柔和，适合灯罩、半透明外壳和装饰件',
    descriptionEn: 'Semi-transparent frosted effect with soft light transmission, suitable for lampshades, translucent housings, and decorative parts',
    densityGPerCm3: 1.3,
    materialPricePerG: 1.5,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material8',
    name: '【黑料】Union Black',
    process: 'sla',
    description: '纯黑色泽均匀，表面质感好，适合黑色外观件和展示模型',
    descriptionEn: 'Uniform pure black color with good surface texture, suitable for black appearance parts and display models',
    densityGPerCm3: 1.3,
    materialPricePerG: 1,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material9',
    name: '【咖啡色】UTR3008',
    process: 'sla',
    description: '咖啡色质感独特，表面细腻，适合个性化外观件和艺术模型',
    descriptionEn: 'Distinctive coffee-brown finish with fine surface quality, suitable for customized appearance parts and art models',
    densityGPerCm3: 1.3,
    materialPricePerG: 1,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material10',
    name: '【精细白料】KT100',
    process: 'sla',
    description: '超高精度，表面细腻洁白，适合精细模型和珠宝蜡模',
    descriptionEn: 'Ultra-high precision with a fine white surface, suitable for detailed models and jewelry wax patterns',
    densityGPerCm3: 1.3,
    materialPricePerG: 1,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material11',
    name: '【白料】UTR9118',
    process: 'sla',
    description: '通用型白色树脂，成型精度高，适合各类外观件和结构验证',
    descriptionEn: 'General-purpose white resin with high forming accuracy, suitable for appearance parts and structural validation',
    densityGPerCm3: 1.3,
    materialPricePerG: 0.5,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material12',
    name: '【耐温料】UFSH220',
    process: 'sla',
    description: '超高耐温性，热变形温度优异，适合高温工况下的功能部件',
    descriptionEn: 'Ultra-high heat resistance and excellent heat deflection performance, suitable for functional components under high-temperature conditions',
    densityGPerCm3: 1.3,
    materialPricePerG: 4,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material13',
    name: '【黑料】Ledo8080',
    process: 'sla',
    description: '黑色高韧性树脂，抗冲击性好，适合黑色功能件和结构件',
    descriptionEn: 'Black high-toughness resin with good impact resistance, suitable for black functional parts and structural parts',
    densityGPerCm3: 1.3,
    materialPricePerG: 1.5,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material14',
    name: '【FDM】PEEK',
    process: 'fdm',
    description: '超高强度、耐高温、耐化学腐蚀，适合航空航天和医疗级高性能部件',
    descriptionEn: 'Ultra-high strength, heat resistance, and chemical resistance, suitable for aerospace and medical-grade high-performance components',
    densityGPerCm3: 1.3,
    materialPricePerG: 12,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material15',
    name: '【金属】铝合金（ AlSi10Mg）',
    process: 'slm',
    description: '轻量化、高强度、导热性好，适合航空航天和汽车零部件',
    descriptionEn: 'Lightweight, high strength, and good thermal conductivity, suitable for aerospace and automotive components',
    densityGPerCm3: 3,
    materialPricePerG: 3,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material16',
    name: '【金属】钛合金（TC4）',
    process: 'slm',
    description: '高强度、低密度、生物相容性优异，适合医疗植入物和航空部件',
    descriptionEn: 'High strength, low density, and excellent biocompatibility, suitable for medical implants and aerospace components',
    densityGPerCm3: 4.5,
    materialPricePerG: 12,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material17',
    name: '【金属】不锈钢316L',
    process: 'slm',
    description: '优异的耐腐蚀性和生物相容性，适合医疗、食品和化工行业部件',
    descriptionEn: 'Excellent corrosion resistance and biocompatibility, suitable for medical, food, and chemical industry components',
    densityGPerCm3: 8,
    materialPricePerG: 2,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material18',
    name: '【金属】模具钢（MS1）',
    process: 'slm',
    description: '高硬度、高耐磨性，适合注塑模具、冲压模具和工装夹具',
    descriptionEn: 'High hardness and wear resistance, suitable for injection molds, stamping dies, and tooling fixtures',
    densityGPerCm3: 8,
    materialPricePerG: 2.5,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material19',
    name: '【金属】铝合金（ 6061）',
    process: 'slm',
    description: '综合力学性能优异，易加工，适合通用结构件和机械零件',
    descriptionEn: 'Excellent overall mechanical properties and machinability, suitable for general structural parts and mechanical components',
    densityGPerCm3: 3,
    materialPricePerG: 3,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material20',
    name: '【尼龙】HP尼龙玻纤PA12GF30',
    process: 'mjf',
    description: '玻纤增强，强度和刚性大幅提升，适合高强度功能件和结构件',
    descriptionEn: 'Glass-fiber reinforced with significantly improved strength and stiffness, suitable for high-strength functional and structural parts',
    densityGPerCm3: 1.41,
    materialPricePerG: 2.5,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material21',
    name: '【尼龙】HP尼龙PA12',
    process: 'mjf',
    description: '表面光滑，力学性能均衡，适合小批量生产功能件',
    descriptionEn: 'Smooth surface with balanced mechanical properties, suitable for small-batch production functional parts',
    densityGPerCm3: 1.3,
    materialPricePerG: 2,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material22',
    name: '【SLS】TPU01',
    process: 'sls',
    description: '高弹性、耐磨损，适合柔性部件、减震件和密封件',
    descriptionEn: 'High elasticity and wear resistance, suitable for flexible parts, shock absorbers, and seals',
    densityGPerCm3: 1.3,
    materialPricePerG: 3,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material23',
    name: '【尼龙】尼龙PA12-白色',
    process: 'sls',
    description: '综合性能好，韧性佳，适合通用功能件和小批量生产',
    descriptionEn: 'Good overall performance and toughness, suitable for general functional parts and small-batch production',
    densityGPerCm3: 1.3,
    materialPricePerG: 1.5,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material24',
    name: '【尼龙】尼龙PA12-黑色',
    process: 'sls',
    description: '黑色耐候性好，韧性优异，适合户外使用的功能件',
    descriptionEn: 'Black material with good weather resistance and excellent toughness, suitable for outdoor functional parts',
    densityGPerCm3: 1.3,
    materialPricePerG: 1.5,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material25',
    name: '【尼龙】尼龙加玻纤PA12+35%GF本色',
    process: 'sls',
    description: '玻纤增强，高强度、高刚性，适合重载结构件',
    descriptionEn: 'Glass-fiber reinforced with high strength and stiffness, suitable for heavy-duty structural parts',
    densityGPerCm3: 1.41,
    materialPricePerG: 1.8,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material26',
    name: '【尼龙】尼龙加玻纤PA12+35%GF黑',
    process: 'sls',
    description: '黑色玻纤增强，强度高、耐候性好，适合重载户外结构件',
    descriptionEn: 'Black glass-fiber reinforced material with high strength and good weather resistance, suitable for heavy-duty outdoor structural parts',
    densityGPerCm3: 1.41,
    materialPricePerG: 1.8,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  },
  {
    id: 'material27',
    name: '【尼龙】尼龙PA6+GF-灰黑色',
    process: 'sls',
    description: '基材加玻纤，刚性更高、耐磨性好，适合耐磨结构件',
    descriptionEn: 'Glass-fiber reinforced base material with higher stiffness and good wear resistance, suitable for wear-resistant structural parts',
    densityGPerCm3: 1.3,
    materialPricePerG: 4.5,
    surfaceAreaPricePerMm2: 0.0001,
    supportRate: 0,
    failureRate: 0.06,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.3,
    leadTimeDays: 2,
    enabled: true
  }
];

